@extends('layouts.app')
@section('title', 'Fleet assistant')
@section('content')
<div class="page-heading"><p class="muted">Need detailed vehicle and driver history?</p><a class="primary" href="{{ route('movement.index') }}">Analyze vehicle movements →</a></div>
<section class="executive-banner"><div><span class="hero-kicker">TEVERA INTELLIGENCE</span><h1>A clearer view.<br>A smarter next step.</h1><p>Understand your fleet setup and get help with the next task.</p></div><span class="ai-orbit" aria-hidden="true">✦</span></section>
<div class="assistant-layout"><section class="panel assistant-panel"><div class="panel-heading"><h2>Fleet assistant</h2><span class="badge neutral">{{ $ready ? 'Connected' : 'Setup required' }}</span></div>
@if(session('assistant_answer'))<div class="assistant-question">{{ session('assistant_question') }}</div><div class="assistant-answer"><span class="hero-kicker">TEVERA AI</span><p>{{ session('assistant_answer') }}</p></div>@else<div class="assistant-welcome"><span class="assistant-spark" aria-hidden="true">✦</span><h2>What would you like to understand?</h2><p class="muted">Try “Explain my fleet setup counts” or “Why is my linked tracker not showing a location?”</p></div>@endif
@if(!$ready)<p class="notice">AI is not connected yet. Your fleet snapshot and setup guide are available now.</p>@endif
<form class="fleet-form assistant-compose" action="{{ route('assistant.ask') }}" method="POST">@csrf<label for="ai-question">Your question<textarea id="ai-question" name="question" rows="4" maxlength="1200" required placeholder="Ask about fleet setup or your workspace counts…" @disabled(!$ready)></textarea></label><label class="checkbox"><input type="checkbox" name="include_summary" value="1"> Include the four fleet counts shown here</label><p class="muted">Your question and any selected counts are sent to the configured AI provider ({{ config('ai.provider') }}). Vehicle identifiers, locations, names and credentials are not automatically included. Avoid putting sensitive information in your question.</p><button class="primary" @disabled(!$ready)>Ask TEVERA <span aria-hidden="true">✦</span></button></form><p class="section-caption">Read-only assistance. Check suggestions before acting. Each question is independent; this assistant has no live GPS or trip history.</p>
@can('manage-platform')@if(!$ready)<details><summary>Connect the AI provider</summary><p>Set <code>AI_ENABLED=true</code>, <code>AI_PROVIDER</code>, <code>AI_MODEL</code>, <code>AI_BASE_URL</code> and, if required, <code>AI_API_KEY</code> in your private environment configuration. Providers: openai, anthropic, gemini, compatible (Chat Completions), or ollama (local models). Rebuild configuration after changing it. Keep keys out of browser code.</p></details>@endif
@endcan</section>
<aside><section class="panel fleet-section"><span class="eyebrow accent">WORKSPACE SNAPSHOT</span><h2>Your fleet, in focus</h2><dl class="workspace-details"><div><dt>Vehicles</dt><dd>{{ $summary['vehicles'] }}</dd></div><div><dt>Enabled vehicles</dt><dd>{{ $summary['enabled_vehicles'] }}</dd></div><div><dt>Linked devices</dt><dd>{{ $summary['linked_devices'] }}</dd></div><div><dt>Sync needs attention</dt><dd>{{ $summary['sync_attention'] }}</dd></div></dl><p class="muted">{{ $summary['sync_attention'] ? 'Some device records need synchronization. Open Vehicles to review their status.' : 'No pending or failed synchronization records in your visible fleet.' }}</p><p class="section-caption">Database snapshot, not AI-generated. Enabled does not mean online.</p><a class="subtle-link" href="{{ route('vehicles.index') }}">Review vehicles →</a></section><section class="panel"><h2>Get connected</h2><p class="muted">Follow the device setup guide to register a tracker and confirm its first location.</p><a class="secondary" href="{{ route('tracker.setup') }}">Tracker setup guide</a></section></aside></div>
@endsection
