@extends('layouts.app')
@section('title', $devices ? 'GPS devices' : 'Vehicles')
@section('content')
<div class="page-heading"><div><div class="eyebrow accent">FLEET MANAGEMENT</div><h1>{{ $devices ? 'GPS devices' : 'Vehicles' }}</h1><p class="muted">Your fleet, tracker identifiers and customer assignments in one place.</p></div>@can('create', \App\Models\Vehicle::class)<a class="primary" href="{{ route('vehicles.create') }}">+ Add vehicle / GPS device</a>@endcan</div>
@if($connectionError)<div class="notice error">{{ $connectionError }} Device status may be unavailable.</div>@endif
<div class="panel fleet-panel">
<form method="GET" class="fleet-filter"><label for="fleet-search">Search vehicles or tracker ID<input id="fleet-search" name="search" value="{{ request('search') }}" placeholder="Name, registration or IMEI"></label><label for="fleet-status">Status<select id="fleet-status" name="status"><option value="">All</option><option value="active" @selected(request('status') === 'active')>Active</option><option value="inactive" @selected(request('status') === 'inactive')>Deactivated</option></select></label><button class="secondary">Apply filters</button></form>
<div class="table-scroll"><table class="fleet-table"><thead><tr><th>Vehicle</th><th>{{ $devices ? 'Tracker ID / IMEI' : 'Registration' }}</th><th>Customer</th><th>{{ $devices ? 'Tracker model' : 'Driver' }}</th><th>GPS status / last report</th><th>Sync</th><th>Account status</th><th></th></tr></thead><tbody>
@forelse($vehicles as $vehicle)
<tr><td><strong>{{ $vehicle->name }}</strong>@if($devices)<small>{{ $vehicle->registration }} · {{ $vehicle->tracker_protocol ?: 'Protocol not recorded' }}</small>@else<small>{{ $vehicle->make }} {{ $vehicle->model }}</small>@endif</td><td>{{ $devices ? $vehicle->unique_id : $vehicle->registration }}</td><td>{{ $vehicle->customer->name }}</td><td>{{ $devices ? ($vehicle->tracker_model ?: 'Not recorded') : ($vehicle->driver?->name ?? 'Unassigned') }}</td><td>{{ ucfirst($deviceData->get($vehicle->traccar_device_id)["status"] ?? "unknown") }}<small>{{ $deviceData->get($vehicle->traccar_device_id)["lastUpdate"] ?? "No report yet" }}</small>@if($position = $positionData->get($vehicle->traccar_device_id))<small>{{ $position["latitude"] ?? "—" }}, {{ $position["longitude"] ?? "—" }}</small>@endif</td><td><span class="badge {{ $vehicle->sync_status === 'synced' ? '' : 'neutral' }}">{{ ucfirst($vehicle->sync_status ?? 'pending') }}</span></td><td>{{ $vehicle->is_active ? 'Active' : 'Deactivated' }}</td><td>@can('update', $vehicle)<a href="{{ route('vehicles.edit', $vehicle) }}">Manage →</a>@else<a href="{{ route('tracking') }}">View map →</a>@endcan</td></tr>
@empty
<tr><td colspan="8"><div class="fleet-empty"><h2>No {{ $devices ? 'GPS devices' : 'vehicles' }} yet</h2><p>Add a customer workspace, then register a vehicle with the identifier sent by its GPS tracker.</p>@can('create', \App\Models\Vehicle::class)<a class="secondary" href="{{ route('vehicles.create') }}">Add your first vehicle</a>@endcan</div></td></tr>
@endforelse
</tbody></table></div><div class="fleet-pagination">{{ $vehicles->links() }}</div>
</div>
<section class="panel fleet-note"><h2>How GPS tracking connects</h2><p>Use the exact device identifier configured in the tracker—often its IMEI. Configure that tracker to send to your reachable server address and the port for its Traccar protocol. Positions appear on the map after the first valid GPS report.</p><a href="{{ route('protocols.index') }}">View supported protocols and ports →</a></section>
@endsection
