@extends('layouts.app')
@section('title','Fleet operations')
@section('content')
<div class="page-heading"><div><h1>Fleet operations</h1><p class="muted">Control running costs, keep vehicles ready, and keep customers informed.</p></div></div>
<nav class="ops-tabs" aria-label="Fleet operations">@foreach(['fuel'=>'Fuel & costs','maintenance'=>'Maintenance','sharing'=>'Customer links','reports'=>'Reports & driver scores'] as $key=>$label)<a class="{{ $tab===$key ? 'primary' : 'secondary' }}" href="{{ route('operations.index',['tab'=>$key]) }}">{{ $label }}</a>@endforeach</nav>
@if($tab==='fuel')
<section class="panel ops-panel"><h2>Record a fill-up</h2><form class="fleet-form" method="POST" action="{{ route('operations.fuel') }}">@csrf
<div class="fleet-grid"><label>Vehicle<select name="vehicle_id" required>@foreach($vehicles as $v)<option value="{{ $v->id }}">{{ $v->name }} Â· {{ $v->registration }}</option>@endforeach</select></label><label>Date<input type="date" name="filled_on" value="{{ old('filled_on',date('Y-m-d')) }}" required></label><label>Litres<input type="number" name="litres" min="0.01" step="0.01" required value="{{ old('litres') }}"></label><label>Odometer (km)<input type="number" name="odometer" min="0" step="0.1" required value="{{ old('odometer') }}"></label><label>Total cost<input type="number" name="cost" min="0" step="0.01" required value="{{ old('cost') }}"></label><label>Currency<select name="currency"><option value="USD">USD</option><option value="ZWG">ZiG (ZWG)</option></select></label></div>
<label class="checkbox"><input type="checkbox" name="full_tank" value="1"> Tank filled completely</label><label>Receipt reference / notes<input name="notes" maxlength="500" value="{{ old('notes') }}"></label><button class="primary">Save fill-up</button></form></section>
<section class="panel ops-panel"><h2>Vehicle cost comparison</h2><p class="muted">Consumption uses consecutive full-tank readings and includes partial fills between them. Record every fill-up. Currencies stay separate; no automatic exchange rate is assumed.</p><div class="table-scroll"><table class="fleet-table"><thead><tr><th>Vehicle</th><th>Fuel purchased</th><th>Recorded cost</th><th>Consumption</th></tr></thead><tbody>@forelse($costs as $cost)<tr><td>{{ $vehicles->firstWhere('id',$cost->vehicle_id)?->name }}</td><td>{{ number_format($cost->litres,2) }} L</td><td>{{ $cost->currency }} {{ number_format($cost->cost/100,2) }}</td><td>{{ isset($consumption[$cost->vehicle_id]) ? $consumption[$cost->vehicle_id].' L/100 km' : 'Needs two full-tank readings' }}</td></tr>@empty<tr><td colspan="4">Record your first fill-up to compare running costs.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel ops-panel"><h2>Fuel log</h2><div class="table-scroll"><table class="fleet-table"><thead><tr><th>Date</th><th>Vehicle</th><th>Litres</th><th>Odometer</th><th>Cost</th><th>Notes</th></tr></thead><tbody>@forelse($fuel as $entry)<tr><td>{{ $entry->filled_on }}</td><td>{{ $vehicles->firstWhere('id',$entry->vehicle_id)?->name }}</td><td>{{ $entry->litres }} {{ $entry->full_tank ? '(full)' : '' }}</td><td>{{ $entry->odometer }} km</td><td>{{ $entry->currency }} {{ number_format($entry->cost_cents/100,2) }}</td><td>{{ $entry->notes }}</td></tr>@empty<tr><td colspan="6">No fill-ups yet.</td></tr>@endforelse</tbody></table></div>{{ $fuel->appends(['tab'=>$tab])->links() }}</section>
@elseif($tab==='maintenance')
<section class="panel ops-panel"><h2>Plan a service</h2><form class="fleet-form" method="POST" enctype="multipart/form-data" action="{{ route('operations.maintenance') }}">@csrf<div class="fleet-grid"><label>Vehicle<select name="vehicle_id" required>@foreach($vehicles as $v)<option value="{{ $v->id }}">{{ $v->name }} Â· {{ $v->odometer }} km</option>@endforeach</select></label><label>Service / repair<input name="title" required maxlength="150" value="{{ old('title') }}"></label><label>Due date<input type="date" name="due_on" value="{{ old('due_on') }}"></label><label>Due at odometer (km)<input type="number" name="due_odometer" min="0" step="0.1" value="{{ old('due_odometer') }}"></label></div><p class="muted">Set a date, mileage, or both. Mileage reminders use the vehicle's recorded odometer; update it when servicing or recording fuel.</p><label>Notes<textarea name="notes" maxlength="5000">{{ old('notes') }}</textarea></label><label>Service document (PDF, JPG or PNG, up to 5 MB)<input type="file" name="document" accept=".pdf,.jpg,.jpeg,.png"></label><button class="primary">Create reminder</button></form></section>
<section class="panel ops-panel"><h2>Service schedule & history</h2><div class="ops-cards">@forelse($tasks as $task)@php($vehicle=$vehicles->firstWhere('id',$task->vehicle_id))@php($due=!$task->completed_at && (($task->due_on && $task->due_on<=date('Y-m-d')) || ($task->due_odometer!==null && $task->due_odometer<=$vehicle?->odometer)))<article class="ops-card"><span class="badge">{{ $task->completed_at ? 'Completed' : ($due ? 'Service due' : 'Scheduled') }}</span><h3>{{ $task->title }}</h3><p>{{ $vehicle?->name }}</p><p class="muted">{{ $task->due_on ?? 'No date set' }} Â· {{ $task->due_odometer!==null ? $task->due_odometer.' km' : 'No mileage set' }}</p><p>{{ $task->notes }}</p>@if($task->document_path)<a class="subtle-link" href="{{ route('operations.document',$task->id) }}">Download service document</a>@endif
@if($task->completed_at)<p>Completed {{ $task->completed_at }} Â· {{ $task->currency }} {{ number_format($task->cost_cents/100,2) }}</p>@else<form method="POST" action="{{ route('operations.complete',$task->id) }}" class="fleet-form">@csrf<label>Repair/service cost<input type="number" name="cost" min="0" step="0.01" required></label><label>Currency<select name="currency"><option>USD</option><option value="ZWG">ZiG (ZWG)</option></select></label><button class="secondary">Mark completed</button></form>@endif</article>@empty<p>No maintenance tasks yet.</p>@endforelse</div>{{ $tasks->appends(['tab'=>$tab])->links() }}</section>
@elseif($tab==='sharing')
@if(session('share_url'))<section class="panel ops-panel"><h2>Your new tracking link</h2><p>Copy this link now. It is shown only once.</p><input aria-label="Tracking link" readonly value="{{ session('share_url') }}"><a href="{{ session('share_url') }}" target="_blank" rel="noreferrer">Preview link</a></section>@endif
<section class="panel ops-panel"><h2>Share a delivery location</h2><p class="muted">The recipient sees the label and latest location only. Anyone holding the link can open it. Share it only with the intended customer.</p><form class="fleet-form" method="POST" action="{{ route('shares.store') }}">@csrf<div class="fleet-grid"><label>Vehicle<select name="vehicle_id" required>@foreach($vehicles->where('is_active',true)->whereNotNull('traccar_device_id') as $v)<option value="{{ $v->id }}">{{ $v->name }}</option>@endforeach</select></label><label>Customer-facing label<input name="label" placeholder="Your delivery" maxlength="100" required></label><label>Expires in hours<input type="number" name="hours" value="4" min="1" max="168" required></label></div><button class="primary">Create tracking link</button></form></section>
<section class="panel ops-panel"><h2>Shared links</h2><div class="table-scroll"><table class="fleet-table"><thead><tr><th>Label</th><th>Vehicle</th><th>Expires UTC</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($shares as $share)<tr><td>{{ $share->label }}</td><td>{{ $vehicles->firstWhere('id',$share->vehicle_id)?->name }}</td><td>{{ $share->expires_at }}</td><td>{{ $share->revoked_at ? 'Revoked' : (\Carbon\Carbon::parse($share->expires_at)->isPast() ? 'Expired' : 'Active') }}</td><td>@if(!$share->revoked_at && \Carbon\Carbon::parse($share->expires_at)->isFuture())<form method="POST" action="{{ route('shares.revoke',$share->id) }}">@csrf<button class="secondary">Revoke</button></form>@endif</td></tr>@empty<tr><td colspan="5">No links created.</td></tr>@endforelse</tbody></table></div>{{ $shares->appends(['tab'=>$tab])->links() }}</section>
@else
<section class="panel ops-panel"><h2>Journey report & driver scorecard</h2><p class="muted">Choose up to seven days. Scores describe recorded vehicle events, attributed to the currently assigned driver; they do not prove who drove past trips.</p><form class="fleet-form" method="GET" action="{{ route('operations.report') }}"><div class="fleet-grid"><label>Vehicle<select name="vehicle_id" required>@foreach($vehicles as $v)<option value="{{ $v->id }}">{{ $v->name }}</option>@endforeach</select></label><label>From (UTC)<input type="date" name="from" value="{{ date('Y-m-d') }}" required></label><label>Through (UTC)<input type="date" name="to" value="{{ date('Y-m-d') }}" required></label><label>Output<select name="format"><option value="html">View scorecard</option><option value="csv">Download CSV</option></select></label></div><button class="primary">Generate report</button></form></section>
<section class="panel ops-panel"><h2>Scheduled fleet summaries</h2><p class="muted">Daily or weekly summaries include distance, idle time, driving events, and overdue servicing for your accessible active vehicles. Delivered to {{ auth()->user()->email }} at the next scheduled run after 06:00 server time.</p><form class="fleet-form" method="POST" action="{{ route('operations.schedule') }}">@csrf<label>Frequency<select name="frequency">@foreach(['off'=>'Off','daily'=>'Daily','weekly'=>'Weekly'] as $key=>$label)<option value="{{ $key }}" @selected(($schedule->frequency ?? 'off')===$key)>{{ $label }}</option>@endforeach</select></label><button class="primary">Save schedule</button></form>@if($schedule)<p class="muted">Next run: {{ $schedule->next_run_at }} Â· Last result: {{ $schedule->last_status ?? 'Not run yet' }}</p>@endif</section>
@endif
@endsection
