@extends('layouts.app')
@section('title', 'Tracker setup guide')
@section('content')
<div class="page-heading"><div><div class="eyebrow accent">CONNECT YOUR FIRST TRACKER</div><h1>From device to map.</h1><p class="muted">Follow these steps to link a vehicle tracker or phone to TEVERA.</p></div><a class="primary" href="{{ route('vehicles.create') }}">Add vehicle / device</a></div>
<section class="panel fleet-section"><h2>1. Find your device's protocol</h2><p>Check the exact make and model against the <a href="https://www.traccar.org/devices/" target="_blank" rel="noopener noreferrer">official Traccar device list</a>. Similar-looking trackers can use different protocols. Then select the matching protocol below.</p>
<form method="GET" action="{{ route('tracker.setup') }}" class="fleet-form"><div class="fleet-grid"><label for="setup-protocol">Tracker protocol<select id="setup-protocol" name="protocol">@foreach($protocols as $protocol)<option value="{{ $protocol['name'] }}" @selected($selected && $selected['name'] === $protocol['name'])>{{ $protocol['name'] }}</option>@endforeach</select></label></div><button class="secondary">Show connection details</button></form></section>
<section class="panel fleet-section"><h2>2. Use your tracker connection details</h2><div class="table-scroll"><table class="fleet-table"><tbody><tr><th>Server address</th><td>@if($trackerHost)<code>{{ $trackerHost }}</code>@else<strong>Not configured yet</strong><p>Ask your platform administrator for the address the tracker can reach.</p>@endif</td></tr><tr><th>Protocol</th><td>{{ $selected['name'] ?? 'Select a protocol above' }}</td></tr><tr><th>Receiver port</th><td><strong>{{ $port ?? 'Select a protocol above' }}</strong></td></tr><tr><th>Device identifier</th><td>The exact ID sent by the device. Often an IMEI, but some models send another identifier. Preserve leading zeros.</td></tr><tr><th>TCP or UDP</th><td>Use the transport specified for your model and make sure that same transport is enabled on the server.</td></tr></tbody></table></div><p class="muted">These are configured reference values, not a connectivity test. Your administrator must enable the receiver, publish its port and allow it through the firewall. Port 8082 is the private API, not the tracker receiver.</p>
<details><summary>Testing on this Windows computer?</summary><p>A device cannot reach this PC using <code>127.0.0.1</code> or <code>localhost</code>: those names refer to the device itself. For a phone on the same Wi-Fi, use this PC's LAN IP and permit the receiver port through Windows Firewall. For a tracker using cellular data, use a reachable public server or an appropriate private network. A local website working does not prove GPS ports are reachable.</p></details>
@can('manage-platform')<details><summary>Set the address shown to your companies</summary><p>Set <code>TRACCAR_DEVICE_HOST</code> to the tracker-facing hostname or IP in the private environment configuration. Set <code>TRACCAR_CLIENT_URL</code> separately to the full phone receiver URL. Neither value should contain API credentials. For Docker, edit <code>deploy/.env</code> and run <code>./tevera start</code>; for the local app, edit <code>platform/.env</code> and clear the configuration cache.</p></details>@endcan</section>
<div class="overview-grid premium-overview"><section class="panel fleet-section"><h2>3. Register the vehicle in TEVERA</h2><ol class="setup-steps"><li>Open <a href="{{ route('vehicles.create') }}">Add vehicle / device</a> and select the correct company if you are a platform administrator.</li><li>Enter the vehicle name, registration and exact tracker identifier. Record the model, SIM number and protocol.</li><li>Save and check that device synchronization succeeds. If it fails, resolve the reported error before retrying.</li><li>Assign operator/customer users who should see this vehicle.</li></ol><p class="muted">Entering an IMEI does not locate a device by itself. The tracker must send its GPS reports to your server.</p></section>
<section class="panel fleet-section"><h2>4. Configure the physical tracker</h2><ol class="setup-steps"><li>Power the tracker and fit an active, compatible data SIM.</li><li>Set the SIM's APN and any required APN username/password using details supplied by the mobile operator.</li><li>Using the manufacturer's app, USB tool or documented SMS commands, enter the server address, receiver port and correct transport.</li><li>Enable location reporting and choose an interval appropriate for your fleet and data allowance.</li><li>Test outdoors with GPS reception and mobile coverage.</li></ol><p class="muted">SMS command syntax and device passwords vary by model and firmware. Follow the exact manufacturer's manual; there is no universal setup command.</p></section></div>
<section class="panel fleet-section"><h2>Using a phone instead?</h2><p>Install <a href="https://www.traccar.org/client/" target="_blank" rel="noopener noreferrer">Traccar Client</a> on a phone you are authorized to track. Register the identifier shown in the app as the vehicle's tracker ID in TEVERA.</p><p><strong>Phone server URL:</strong> @if($clientUrl)<code>{{ $clientUrl }}</code>@else Not configured — ask your administrator for the full receiver URL.@endif</p><p>Traccar Client uses the OsmAnd receiver (configured port <strong>{{ $phonePort }}</strong>). Enter a full URL, including its scheme and port where needed. Use the phone receiver address rather than TEVERA's login URL. Grant location/background permissions and start reporting. For same-Wi-Fi testing only, an example is <code>http://YOUR-PC-LAN-IP:{{ $phonePort }}</code>; replace the placeholder. Public HTTPS needs a receiver endpoint configured for it.</p><a href="https://www.traccar.org/client-configuration/" target="_blank" rel="noopener noreferrer">Official phone configuration instructions</a></section>
<section class="panel fleet-section"><h2>5. Confirm the first location</h2><p>Open <a href="{{ route('tracking') }}">Vehicle map</a> and select <strong>Refresh positions</strong>. Find your vehicle and check its GPS time and coordinates. A linked device can still be waiting for its first valid position.</p><div class="table-scroll"><table class="fleet-table"><thead><tr><th>What you see</th><th>What to check</th></tr></thead><tbody><tr><td>Device sync failed</td><td>Check the error on the vehicle. Confirm Traccar connectivity and that the identifier is not already registered to another device.</td></tr><tr><td>Linked, but no location</td><td>Check the device ID, protocol, port, transport, APN/data balance, reporting settings and GPS reception.</td></tr><tr><td>Vehicle missing from the list</td><td>Check the selected company and vehicle assignments. Clear map filters and check other pages.</td></tr><tr><td>Old location / offline</td><td>Check power, coverage and reporting interval. Compare GPS time with server time, then refresh again.</td></tr><tr><td>Vehicle details appear but map tiles do not</td><td>Check browser internet access. Map tiles and tracker reports are separate connections.</td></tr></tbody></table></div></section>
@endsection
