@extends('layouts.app')
@section('title', 'Subscription & billing')
@section('content')
<div class="page-heading"><div><div class="eyebrow accent">TEVERA SUBSCRIPTIONS</div><h1>Subscription & billing</h1><p class="muted">Payments processed by Paynow for {{ config('paynow.merchant') }}.</p></div>@if($super)<a class="primary" href="{{ route('plans.index') }}">Manage plans</a>@endif</div>
@if(!$ready)<div class="notice">Checkout is awaiting merchant configuration. Your administrator can configure plans before enabling payments.</div>@endif
@if($customer)<section class="panel fleet-section"><h2>{{ $customer->name }}</h2><p>{{ $customer->billing_required ? ($customer->subscriptionAllowsAccess() ? 'Subscription access active' : 'Renewal required') : 'Managed workspace — subscription enforcement off' }}</p><p>Paid access until: {{ $customer->subscription_expires_at?->format('d M Y H:i') ?? 'No paid subscription' }} · Trial until: {{ $customer->trial_ends_at?->format('d M Y') ?? 'No trial' }}</p><p>Vehicle allowance: {{ $customer->vehicle_limit ?? 'Unlimited' }}</p></section>@endif
@if(auth()->user()->role === \App\Enums\Role::Admin)
<div class="stats-grid premium-stats">@forelse($plans as $plan)<section class="panel"><h2>{{ $plan->name }}</h2><h3>{{ $plan->currency }} {{ number_format($plan->amount_cents / 100, 2) }}</h3><p>{{ $plan->billing_months == 12 ? 'Yearly' : ($plan->billing_months == 1 ? 'Monthly' : 'Every 30 days') }} · {{ $plan->vehicle_limit }} vehicles</p><form method="POST" action="{{ route('billing.checkout') }}">@csrf<input type="hidden" name="plan_id" value="{{ $plan->id }}"><button class="primary" @disabled(!$ready)>Choose / renew</button></form></section>@empty<p>No published plans yet. Contact your platform administrator.</p>@endforelse</div><p class="muted">Renewals require a new Paynow payment. There are no automatic charges. An early renewal extends your current paid period by the purchased billing period.</p>
@elseif(!$super)<p>Your company administrator manages subscriptions and payment receipts.</p>@endif
<section class="panel fleet-section"><h2>More than 10 vehicles?</h2><p class="muted">Contact your platform administrator for a custom company quote. Monthly and yearly company plans include the same platform features. GPS hardware, SIM/data and installation are charged separately.</p></section>
@can('manage-users')<section class="panel"><h2>{{ $super ? 'All company payments' : 'Payment history' }}</h2><div class="table-scroll"><table class="fleet-table"><thead><tr><th>Reference</th>@if($super)<th>Company ID</th>@endif<th>Plan</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td><a href="{{ route('billing.payment', $payment) }}">{{ $payment->id }}</a></td>@if($super)<td>{{ $payment->customer_id }}</td>@endif<td>{{ $payment->plan_name }}</td><td>{{ $payment->currency }} {{ number_format($payment->amount_cents / 100, 2) }}</td><td>{{ ucfirst($payment->status) }}</td><td>{{ $payment->created_at->format('d M Y') }}</td></tr>@empty<tr><td colspan="6">No payments yet.</td></tr>@endforelse</tbody></table></div>{{ $payments->links() }}</section>@endcan
@endsection
